export { computeAlignmentScore } from "./alignment-score.js";
export type { AlignmentScore } from "./alignment-score.js";
export { buildDeckIr } from "./build-deck-ir.js";
export { runChecks, collectGroupSafetyFindings } from "./checks.js";
export type { RunChecksResult } from "./checks.js";
export { SAFE_PATCH_OPS, CAUTION_PATCH_OPS, MANUAL_PATCH_OPS, PLAYBOOK_RULE_COUNT } from "./constants.js";
export { scoreExemplarHealth } from "./exemplar-health.js";
export { planPatches } from "./patch-planner.js";
export { reconcilePatches } from "./reconcile.js";
export { inferRoles } from "./role-inference.js";
export { buildStyleSignature } from "./style-signature.js";
export { buildStyleMap } from "./style-map.js";
export { translateFinding, notAnalyzedBucket, NOT_ANALYZED_BUCKET_LABELS } from "./finding-translator.js";
export type { TranslatedFinding, TranslatedFindingRiskLabel, NotAnalyzedBucket } from "./finding-translator.js";
export { inferCandidateRules } from "./infer-rules.js";
export { emitEvent, setTelemetrySink, resetTelemetrySink } from "./telemetry.js";
export type { TelemetryEvent, TelemetrySink } from "./telemetry.js";
